import D from "../images/D.png";
import T from "../images/T.png";
import G from "../images/G.png";
import Dw from "../images/Dw.png";
import H from "../images/H.png";
import Ha from "../images/Ha.png";
import HE from "../images/HE.png";
import HO from "../images/HO.png";
import E from "../images/E.png";

import DB from "../images/D_B.png";
import DBa from "../images/D_Ba.png";
import DC from "../images/D_C.png";
import DD from "../images/D_D.png";
import DF from "../images/D_F.png";
import DM from "../images/D_M.png";
import DP from "../images/D_P.png";
import DR from "../images/D_R.png";
import DRg from "../images/D_Rg.png";
import DS from "../images/D_S.png";
import DW from "../images/D_W.png";
import DWiz from "../images/D_Wiz.png";

import DwB from "../images/Dw_B.png";
import DwBa from "../images/Dw_Ba.png";
import DwC from "../images/Dw_C.png";
import DwD from "../images/Dw_D.png";
import DwF from "../images/Dw_F.png";
import DwM from "../images/Dw_M.png";
import DwP from "../images/Dw_P.png";
import DwR from "../images/Dw_R.png";
import DwRg from "../images/Dw_Rg.png";
import DwS from "../images/Dw_S.png";
import DwW from "../images/Dw_W.png";
import DwWiz from "../images/Dw_Wiz.png";

import EB from "../images/E_B.png";
import EBa from "../images/E_Ba.png";
import EC from "../images/E_C.png";
import ED from "../images/E_D.png";
import EF from "../images/E_F.png";
import EM from "../images/E_M.png";
import EP from "../images/E_P.png";
import ER from "../images/E_R.png";
import ERg from "../images/E_Rg.png";
import ES from "../images/E_S.png";
import EW from "../images/E_W.png";
import EWiz from "../images/E_Wiz.png";

import GB from "../images/G_B.png";
import GBa from "../images/G_Ba.png";
import GC from "../images/G_C.png";
import GD from "../images/G_D.png";
import GF from "../images/G_F.png";
import GM from "../images/G_M.png";
import GP from "../images/G_P.png";
import GR from "../images/G_R.png";
import GRg from "../images/G_Rg.png";
import GS from "../images/G_S.png";
import GW from "../images/G_W.png";
import GWiz from "../images/G_Wiz.png";

import HEB from "../images/HE_B.png";
import HEBa from "../images/HE_Ba.png";
import HEC from "../images/HE_C.png";
import HED from "../images/HE_D.png";
import HEF from "../images/HE_F.png";
import HEM from "../images/HE_M.png";
import HEP from "../images/HE_P.png";
import HER from "../images/HE_R.png";
import HERg from "../images/HE_Rg.png";
import HES from "../images/HE_S.png";
import HEW from "../images/HE_W.png";
import HEWiz from "../images/HE_Wiz.png";

import HOB from "../images/HO_B.png";
import HOBa from "../images/HO_Ba.png";
import HOC from "../images/HO_C.png";
import HOD from "../images/HO_D.png";
import HOF from "../images/HO_F.png";
import HOM from "../images/HO_M.png";
import HOP from "../images/HO_P.png";
import HOR from "../images/HO_R.png";
import HORg from "../images/HO_Rg.png";
import HOS from "../images/HO_S.png";
import HOW from "../images/HO_W.png";
import HOWiz from "../images/HO_Wiz.png";

import HaB from "../images/Ha_B.png";
import HaBa from "../images/Ha_Ba.png";
import HaC from "../images/Ha_C.png";
import HaD from "../images/Ha_D.png";
import HaF from "../images/Ha_F.png";
import HaM from "../images/Ha_M.png";
import HaP from "../images/Ha_P.png";
import HaR from "../images/Ha_R.png";
import HaRg from "../images/Ha_Rg.png";
import HaS from "../images/Ha_S.png";
import HaW from "../images/Ha_W.png";
import HaWiz from "../images/Ha_Wiz.png";

import HB from "../images/H_B.png";
import HBa from "../images/H_Ba.png";
import HC from "../images/H_C.png";
import HD from "../images/H_D.png";
import HF from "../images/H_F.png";
import HM from "../images/H_M.png";
import HP from "../images/H_P.png";
import HR from "../images/H_R.png";
import HRg from "../images/H_Rg.png";
import HS from "../images/H_S.png";
import HW from "../images/H_W.png";
import HWiz from "../images/H_Wiz.png";

import TB from "../images/T_B.png";
import TBa from "../images/T_Ba.png";
import TC from "../images/T_C.png";
import TD from "../images/T_D.png";
import TF from "../images/T_F.png";
import TM from "../images/T_M.png";
import TP from "../images/T_P.png";
import TR from "../images/T_R.png";
import TRg from "../images/T_Rg.png";
import TS from "../images/T_S.png";
import TW from "../images/T_W.png";
import TWiz from "../images/T_Wiz.png";

export {D};
export {T};
export {E};
export {HE};
export {Ha};
export {HO};
export {Dw};
export {H};
export {G};

export {DB};
export {DBa};
export {DC};
export {DD};
export {DF};
export {DM};
export {DP};
export {DR};
export {DRg};
export {DS};
export {DW};
export {DWiz};

export {DwB};
export {DwBa};
export {DwC};
export {DwD};
export {DwF};
export {DwM};
export {DwP};
export {DwR};
export {DwRg};
export {DwS};
export {DwW};
export {DwWiz};

export {EB};
export {EBa};
export {EC};
export {ED};
export {EF};
export {EM};
export {EP};
export {ER};
export {ERg};
export {ES};
export {EW};
export {EWiz};

export {GB};
export {GBa};
export {GC};
export {GD};
export {GF};
export {GM};
export {GP};
export {GR};
export {GRg};
export {GS};
export {GW};
export {GWiz};

export {HEB};
export {HEBa};
export {HEC};
export {HED};
export {HEF};
export {HEM};
export {HEP};
export {HER};
export {HERg};
export {HES};
export {HEW};
export {HEWiz};

export {HOB};
export {HOBa};
export {HOC};
export {HOD};
export {HOF};
export {HOM};
export {HOP};
export {HOR};
export {HORg};
export {HOS};
export {HOW};
export {HOWiz};

export {HaB};
export {HaBa};
export {HaC};
export {HaD};
export {HaF};
export {HaM};
export {HaP};
export {HaR};
export {HaRg};
export {HaS};
export {HaW};
export {HaWiz};

export {HB};
export {HBa};
export {HC};
export {HD};
export {HF};
export {HM};
export {HP};
export {HR};
export {HRg};
export {HS};
export {HW};
export {HWiz};

export {TB};
export {TBa};
export {TC};
export {TD};
export {TF};
export {TM};
export {TP};
export {TR};
export {TRg};
export {TS};
export {TW};
export {TWiz};